/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NeuronId = IDL.Text;
export const AttemptStatus = IDL.Variant({
  'failure' : IDL.Text,
  'pending' : IDL.Null,
  'success' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Hotkey = IDL.Principal;
export const HotkeyAttempt = IDL.Record({
  'status' : AttemptStatus,
  'timestamp' : Timestamp,
  'neuronId' : NeuronId,
  'hotkey' : Hotkey,
});
export const ProposalAttempt = IDL.Record({
  'status' : AttemptStatus,
  'timestamp' : Timestamp,
  'neuronId' : NeuronId,
  'proposalId' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'selectedNeuronId' : IDL.Opt(NeuronId),
  'hotkeyAttempts' : IDL.Vec(HotkeyAttempt),
  'proposalAttempts' : IDL.Vec(ProposalAttempt),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordMotionAttempt' : IDL.Func(
      [NeuronId, IDL.Opt(IDL.Text), AttemptStatus],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([IDL.Opt(NeuronId)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NeuronId = IDL.Text;
  const AttemptStatus = IDL.Variant({
    'failure' : IDL.Text,
    'pending' : IDL.Null,
    'success' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Hotkey = IDL.Principal;
  const HotkeyAttempt = IDL.Record({
    'status' : AttemptStatus,
    'timestamp' : Timestamp,
    'neuronId' : NeuronId,
    'hotkey' : Hotkey,
  });
  const ProposalAttempt = IDL.Record({
    'status' : AttemptStatus,
    'timestamp' : Timestamp,
    'neuronId' : NeuronId,
    'proposalId' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'selectedNeuronId' : IDL.Opt(NeuronId),
    'hotkeyAttempts' : IDL.Vec(HotkeyAttempt),
    'proposalAttempts' : IDL.Vec(ProposalAttempt),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordMotionAttempt' : IDL.Func(
        [NeuronId, IDL.Opt(IDL.Text), AttemptStatus],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([IDL.Opt(NeuronId)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };